### PR TITLE
Allow Laravel 9

### PR DESCRIPTION
**Pull request by DanielGSoftware**
This PR allows for Laravel 9.

### CODE REVIEW

**Comment by DanielGSoftware** [comment]
Php-cs-fixer check fails, tried fixing it but can't find why it's failing... can you maybe have a look @jessarcher ? Thanks, and thank you for this awesome package!

**Comment by jessarcher** [comment]
Hey @DanielGSoftware, thanks for this!

I think I've fixed the php-cs-fixer issue. There was also a weird issue with the combo of Laravel 8, PHP 8.1, and `--prefer-lowest` that I've also fixed.

There's still an annoying dependency issue with the windows tests that I'll need to take a closer look at, but I don't have a windows machine to experiment locally.

**Comment by DanielGSoftware** [comment]
Nice! As for the windows test failing, I do have a windows machine but I don't have access to it till monday. Maybe I can have a look then

**Comment by jessarcher** [comment]
Cool, let me know how you go. If we can't solve it I will probably just remove the Windows tests.

**Comment by DanielGSoftware** [comment]
@jessarcher I tried it on my windows machine, everything worked fine.. so then I made a pr on my own repo to rerun the tests and.. they [all pass!](https://github.com/DanielGSoftware/laravel-castable-data-transfer-object/pull/1) Look's like it fixed itself, just gotta rerun the tests but I can't do that here

**Comment by jessarcher** [comment]
@DanielGSoftware Hah! Awesome! I will get this merged and released. Thanks for your help :)

**Pull request merged**
